language: bash

services:
- docker

env:
  matrix:
  - WORDPRESS_VER=4 PHP_VER=7.3
  - WORDPRESS_VER=4 PHP_VER=7.2
  - WORDPRESS_VER=4 PHP_VER=7.1
  - WORDPRESS_VER=4 PHP_VER=5.6 GITHUB_RELEASE=1

script:
- set -e
- make test
- cp docker.mk Makefile
- tar -czf docker4wordpress.tar.gz docker-compose.yml docker-compose.override.yml docker-sync.yml Makefile .env traefik.yml

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
  - docker4wordpress.tar.gz
  on:
    tags: true
    condition: $GITHUB_RELEASE = 1

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
